# Generated by Django 5.0.1 on 2024-05-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
